"""Add phone_number to property

Revision ID: 5d334c7aece0
Revises: 76fad30da2bc
Create Date: 2026-07-25 12:34:58.320626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d334c7aece0'
down_revision: Union[str, Sequence[str], None] = '76fad30da2bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('phone_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'phone_number')
    # ### end Alembic commands ###
