"""Add owner_id to properties

Revision ID: 7f0ec6ca54b7
Revises: ee129a31d257
Create Date: 2026-07-03 07:23:06.177682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0ec6ca54b7'
down_revision: Union[str, Sequence[str], None] = 'ee129a31d257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'properties', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'owner_id')
    # ### end Alembic commands ###
