"""create sessions table

Revision ID: 83463b4097bd
Revises: 15ddc3475f31
Create Date: 2026-05-29 11:20:32.388168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83463b4097bd'
down_revision: Union[str, Sequence[str], None] = '15ddc3475f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.add_column('sessions', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('sessions', 'platform')
    op.drop_column('sessions', 'lead_name')
    op.drop_column('sessions', 'platform_user_id')
    op.drop_column('sessions', 'messages')
    op.drop_column('sessions', 'lead_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('lead_profile', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('messages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('platform_user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('lead_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('sessions', 'title')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
