"""Add BlacklistedToken model

Revision ID: 8cfdd0fa797a
Revises: 7f0ec6ca54b7
Create Date: 2026-07-24 20:58:42.465151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cfdd0fa797a'
down_revision: Union[str, Sequence[str], None] = '7f0ec6ca54b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
